# Generated by Django 5.1.2 on 2024-10-29 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('peca_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.peca')),
                ('tipo', models.CharField(default='Ar', max_length=50)),
                ('tamanho', models.CharField(default='120mm', max_length=50)),
            ],
            bases=('app.peca',),
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('peca_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.peca')),
                ('nucleos', models.IntegerField()),
                ('clock', models.FloatField()),
            ],
            bases=('app.peca',),
        ),
        migrations.CreateModel(
            name='FonteAlimentacao',
            fields=[
                ('peca_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.peca')),
                ('potencia', models.IntegerField()),
            ],
            bases=('app.peca',),
        ),
        migrations.CreateModel(
            name='Gabinete',
            fields=[
                ('peca_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.peca')),
                ('tipo', models.CharField(max_length=50)),
                ('compatibilidade', models.CharField(max_length=100)),
            ],
            bases=('app.peca',),
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('peca_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.peca')),
                ('memoria', models.IntegerField()),
                ('clock', models.IntegerField()),
            ],
            bases=('app.peca',),
        ),
        migrations.CreateModel(
            name='HD',
            fields=[
                ('peca_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.peca')),
                ('armazenamento', models.IntegerField()),
                ('velocidade', models.IntegerField()),
            ],
            bases=('app.peca',),
        ),
        migrations.CreateModel(
            name='PlacaMae',
            fields=[
                ('peca_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.peca')),
                ('formato', models.CharField(max_length=50)),
                ('chipset', models.CharField(max_length=100)),
            ],
            bases=('app.peca',),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('peca_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.peca')),
                ('gb', models.IntegerField()),
                ('mhz', models.IntegerField()),
            ],
            bases=('app.peca',),
        ),
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('peca_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.peca')),
                ('armazenamento', models.IntegerField()),
                ('velocidade', models.IntegerField()),
            ],
            bases=('app.peca',),
        ),
        migrations.CreateModel(
            name='Ventoinha',
            fields=[
                ('peca_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.peca')),
                ('tamanho', models.IntegerField()),
                ('rpm', models.IntegerField()),
            ],
            bases=('app.peca',),
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pecas', models.ManyToManyField(to='app.peca')),
            ],
        ),
    ]
