# Generated by Django 5.1.2 on 2024-11-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_setup_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='peca',
            name='tdp',
            field=models.IntegerField(null=True),
        ),
    ]
