# Generated by Django 5.1.2 on 2024-11-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_peca_tdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='tdp_total',
            field=models.IntegerField(default=0),
        ),
    ]
