# Generated by Django 5.1.4 on 2024-12-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_setup_tdp_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='chipset',
            new_name='socket',
        ),
        migrations.RenameField(
            model_name='placamae',
            old_name='chipset',
            new_name='socket',
        ),
    ]
