# Generated by Django 5.1.4 on 2024-12-15 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_chipset_cpu_socket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.peca')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.setup')),
            ],
        ),
        migrations.AlterField(
            model_name='setup',
            name='pecas',
            field=models.ManyToManyField(through='app.SetupPeca', to='app.peca'),
        ),
    ]
