# Generated by Django 5.1.4 on 2024-12-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_setuppeca_alter_setup_pecas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='pecas',
            field=models.ManyToManyField(to='app.peca'),
        ),
        migrations.DeleteModel(
            name='SetupPeca',
        ),
    ]
